agentaddress udp:127.0.0.1:161
master agentx
agentXSocket /var/agentx/master
agentXPerms 0660 0550 root frr
view router included .1.3.6.1.2.1.1
view router included .1.3.6.1.2.1.2
view router included .1.3.6.1.2.1.4
view router included .1.3.6.1.2.1.31
rouser monitor authpriv -V router
