#!/usr/sbin/nft -f
flush ruleset

table inet appliance {
  chain input {
    type filter hook input priority filter; policy accept;
    ct state invalid drop
    tcp dport 22 ct state new limit rate over 30/minute burst 20 packets drop
  }
  chain forward {
    type filter hook forward priority filter; policy accept;
    ct state invalid drop
  }
  chain output {
    type filter hook output priority filter; policy accept;
  }
}
