interface: lo
aggregate: src_host,dst_host,src_port,dst_port,proto,tos
plugins: nfprobe
nfprobe_receiver: 127.0.0.1:2055
nfprobe_version: 9
nfprobe_timeouts: tcp=120:udp=60:icmp=60:general=120:maxlife=180
