log_file = /var/log/audit/audit.log
log_format = ENRICHED
log_group = adm
write_logs = yes
local_events = yes
flush = INCREMENTAL_ASYNC
freq = 50
max_log_file = 16
num_logs = 4
max_log_file_action = ROTATE
space_left = 512
space_left_action = SYSLOG
admin_space_left = 128
admin_space_left_action = SYSLOG
disk_full_action = ROTATE
disk_error_action = SYSLOG
