PermitRootLogin no
PermitEmptyPasswords no
PasswordAuthentication yes
KbdInteractiveAuthentication no
PubkeyAuthentication yes
MaxAuthTries 4
LoginGraceTime 30
X11Forwarding no
PermitUserEnvironment no
PermitTunnel no
GatewayPorts no
AllowUsers admin
ClientAliveInterval 300
ClientAliveCountMax 2
